const API_BASE_URL_DEVELOPMENT = "https://localhost:7296";

const ENDPOINTS = {
  TO_HOME: "api/#",
  TO_LOGIN: "api/login",
  TO_REGISTER: "api/register",
  TO_SAVE_ROUTE: "api/saveroute",
  TO_UPDATE_PASSWORD: "api/updatepassword",
  TO_UPDATE_EMAIL: "api/updateemail",
  TO_CREATE_GROUP: "api/group",
  TO_GET_GROUPS_BY_OWNERSHIP: "api/getgroupsbyownership",
};
const development = {
  API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_LOGIN}`,
  API_URL_REGISTER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_REGISTER}`,
  API_URL_SAVE_ROUTE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_SAVE_ROUTE}`,
  API_URL_UPDATE_PASSWORD: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_UPDATE_PASSWORD}`,
  API_URL_UPDATE_EMAIL: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_UPDATE_EMAIL}`,
  API_URL_CREATE_GROUP: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_CREATE_GROUP}`,
  API_URL_GET_GROUPS_BY_OWNERSHIP: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_GET_GROUPS_BY_OWNERSHIP}`,
};
const Constants = development;

export default Constants;
